name: Update Index

on:
  push:
    branches: [ main ]
    paths:
      - '**.tgz'
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the Helm chart source
      - name: Chart Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_PAT }}  # Use PAT for checkout

      # Install Helm
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0

      # Checkout the repository where the chart is stored
      - name: Helm Repository Checkout
        uses: actions/checkout@v2
        with:
          repository: yourorg/helm-chart-repository
          token: ${{ secrets.MY_GITHUB_PAT }}  # Use PAT here too
          fetch-depth: 0
          persist-credentials: true
          ref: main
          path: helm-chart-repository

      # Package the Helm chart
      - name: Helm Package
        run: helm package my-chart --version "0.1.0+$(git rev-parse --short "$GITHUB_SHA")" -d helm-chart-repository

      # Push the new chart to the repository
      - name: Helm Push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}  # Use PAT for push
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          CHART_PACKAGE_NAME="my-chart-0.1.0+$(git rev-parse --short "$GITHUB_SHA").tgz"
          cd helm-chart-repository
          git add "$CHART_PACKAGE_NAME"
          git commit -m "$CHART_PACKAGE_NAME"
          git push origin main
